import { Wellness, WellnessGoal, WellnessAppointment, HealthMetric, Medication, Vital, VitalHistory } from "./types";

export const wellnessPatients: Wellness[] = [
  {
    id: "W001",
    name: "Emma Johnson",
    age: 34,
    gender: "Female",
    bloodType: "A+",
    primaryConcern: "Weight Management & Fitness",
    status: "Thriving",
    enrolledDate: "2026-03-15",
    coordinator: "Sarah Lee",
    phone: "+1 (555) 201-4832",
    email: "emma.j@email.com",
    healthGoals: ["10,000 steps daily", "8 hours sleep", "Drink 8 glasses water"],
    activeMetrics: [
      { id: "M001", patientId: "W001", type: "Steps", value: 8750, unit: "steps", timestamp: "2026-05-07" },
      { id: "M002", patientId: "W001", type: "Water", value: 6, unit: "glasses", timestamp: "2026-05-07" },
    ],
    wellnessScore: 78,
  },
  {
    id: "W002",
    name: "Marcus Brown",
    age: 52,
    gender: "Male",
    bloodType: "O+",
    primaryConcern: "Heart Health & Stress",
    status: "Monitoring",
    enrolledDate: "2026-02-20",
    coordinator: "Dr. James Carter",
    phone: "+1 (555) 302-7741",
    email: "m.brown@email.com",
    healthGoals: ["Reduce stress", "Lower BP", "30 min exercise daily"],
    activeMetrics: [
      { id: "M003", patientId: "W002", type: "HeartRate", value: 72, unit: "bpm", timestamp: "2026-05-07" },
      { id: "M004", patientId: "W002", type: "BloodPressure", value: 138, unit: "mmHg", timestamp: "2026-05-07" },
    ],
    wellnessScore: 62,
  },
  {
    id: "W003",
    name: "Lisa Chen",
    age: 28,
    gender: "Female",
    bloodType: "B+",
    primaryConcern: "Energy & Sleep Quality",
    status: "Thriving",
    enrolledDate: "2026-03-01",
    coordinator: "Emily Watson",
    phone: "+1 (555) 408-9213",
    email: "lisa.c@email.com",
    healthGoals: ["7+ hours sleep", "Balanced meals", "Weekly yoga"],
    activeMetrics: [
      { id: "M005", patientId: "W003", type: "Temperature", value: 98.6, unit: "°F", timestamp: "2026-05-07" },
    ],
    wellnessScore: 85,
  },
  {
    id: "W004",
    name: "Robert Davis",
    age: 61,
    gender: "Male",
    bloodType: "AB+",
    primaryConcern: "Diabetes Management",
    status: "NeedsAttention",
    enrolledDate: "2026-01-10",
    coordinator: "Dr. Priya Sharma",
    phone: "+1 (555) 512-6677",
    email: "r.davis@email.com",
    healthGoals: ["Blood sugar control", "Regular monitoring", "Healthy diet"],
    activeMetrics: [],
    wellnessScore: 45,
  },
  {
    id: "W005",
    name: "Sophia Williams",
    age: 41,
    gender: "Female",
    bloodType: "O-",
    primaryConcern: "Stress & Mental Wellness",
    status: "Monitoring",
    enrolledDate: "2026-02-14",
    coordinator: "Emily Watson",
    phone: "+1 (555) 634-8821",
    email: "sophia.w@email.com",
    healthGoals: ["Daily meditation", "Work-life balance", "Exercise 3x/week"],
    activeMetrics: [
      { id: "M006", patientId: "W005", type: "HeartRate", value: 78, unit: "bpm", timestamp: "2026-05-07" },
    ],
    wellnessScore: 58,
  },
  {
    id: "W006",
    name: "James Patel",
    age: 37,
    gender: "Male",
    bloodType: "B-",
    primaryConcern: "Athletic Performance",
    status: "Thriving",
    enrolledDate: "2026-03-22",
    coordinator: "Sarah Lee",
    phone: "+1 (555) 745-3390",
    email: "james.p@email.com",
    healthGoals: ["Marathon training", "Protein intake 150g/day", "Recovery sleep"],
    activeMetrics: [
      { id: "M007", patientId: "W006", type: "Steps", value: 14200, unit: "steps", timestamp: "2026-05-07" },
      { id: "M008", patientId: "W006", type: "HeartRate", value: 58, unit: "bpm", timestamp: "2026-05-07" },
    ],
    wellnessScore: 92,
  },
  {
    id: "W007",
    name: "Aisha Rahman",
    age: 29,
    gender: "Female",
    bloodType: "A-",
    primaryConcern: "Nutrition & Gut Health",
    status: "Thriving",
    enrolledDate: "2026-04-05",
    coordinator: "Dr. Priya Sharma",
    phone: "+1 (555) 856-2247",
    email: "aisha.r@email.com",
    healthGoals: ["Anti-inflammatory diet", "Probiotic supplements", "Meal prep Sundays"],
    activeMetrics: [
      { id: "M009", patientId: "W007", type: "Water", value: 8, unit: "glasses", timestamp: "2026-05-07" },
    ],
    wellnessScore: 81,
  },
  {
    id: "W008",
    name: "Carlos Martinez",
    age: 56,
    gender: "Male",
    bloodType: "AB-",
    primaryConcern: "Cholesterol & Hypertension",
    status: "NeedsAttention",
    enrolledDate: "2026-01-28",
    coordinator: "Dr. James Carter",
    phone: "+1 (555) 967-5513",
    email: "carlos.m@email.com",
    healthGoals: ["Reduce LDL cholesterol", "DASH diet adherence", "Daily 20 min walk"],
    activeMetrics: [
      { id: "M010", patientId: "W008", type: "BloodPressure", value: 148, unit: "mmHg", timestamp: "2026-05-07" },
    ],
    wellnessScore: 39,
  },
];

export const wellnessGoals: WellnessGoal[] = [
  { id: "G001", patientId: "W001", goalName: "Daily Steps",       targetValue: 10000, currentValue: 8750,  unit: "steps",    deadline: "2026-06-07", status: "Active" },
  { id: "G002", patientId: "W001", goalName: "Water Intake",      targetValue: 8,     currentValue: 6,     unit: "glasses",  deadline: "2026-06-07", status: "Active" },
  { id: "G003", patientId: "W002", goalName: "Blood Pressure",    targetValue: 130,   currentValue: 138,   unit: "mmHg",     deadline: "2026-06-15", status: "Active" },
  { id: "G004", patientId: "W003", goalName: "Sleep Duration",    targetValue: 8,     currentValue: 7.5,   unit: "hours",    deadline: "2026-06-10", status: "Active" },
  { id: "G005", patientId: "W003", goalName: "Weekly Exercise",   targetValue: 3,     currentValue: 3,     unit: "sessions", deadline: "2026-05-31", status: "Completed" },
  { id: "G006", patientId: "W004", goalName: "Blood Sugar",       targetValue: 100,   currentValue: 142,   unit: "mg/dL",    deadline: "2026-06-30", status: "Active" },
  { id: "G007", patientId: "W005", goalName: "Meditation",        targetValue: 30,    currentValue: 22,    unit: "days",     deadline: "2026-06-01", status: "Active" },
  { id: "G008", patientId: "W006", goalName: "Weekly Mileage",    targetValue: 40,    currentValue: 40,    unit: "miles",    deadline: "2026-05-25", status: "Completed" },
  { id: "G009", patientId: "W007", goalName: "Hydration",         targetValue: 8,     currentValue: 8,     unit: "glasses",  deadline: "2026-05-31", status: "Completed" },
  { id: "G010", patientId: "W008", goalName: "Daily Walk",        targetValue: 20,    currentValue: 12,    unit: "minutes",  deadline: "2026-06-20", status: "Active" },
  { id: "G011", patientId: "W006", goalName: "Protein Intake",    targetValue: 150,   currentValue: 130,   unit: "grams",    deadline: "2026-06-07", status: "Active" },
  { id: "G012", patientId: "W001", goalName: "Weight Goal",       targetValue: 65,    currentValue: 68,    unit: "kg",       deadline: "2026-07-01", status: "Active" },
];

export const appointments: WellnessAppointment[] = [
  { id: "A001", patientId: "W001", patientName: "Emma Johnson",    date: "2026-05-14", time: "10:00 AM", type: "Coaching",      coordinator: "Sarah Lee",         status: "Scheduled" },
  { id: "A002", patientId: "W002", patientName: "Marcus Brown",    date: "2026-05-15", time: "2:00 PM",  type: "Follow-up",     coordinator: "Dr. James Carter",  status: "Scheduled" },
  { id: "A003", patientId: "W003", patientName: "Lisa Chen",       date: "2026-05-13", time: "11:30 AM", type: "Consultation",  coordinator: "Emily Watson",      status: "Scheduled" },
  { id: "A004", patientId: "W004", patientName: "Robert Davis",    date: "2026-05-16", time: "3:30 PM",  type: "Assessment",    coordinator: "Dr. Priya Sharma",  status: "Scheduled" },
  { id: "A005", patientId: "W005", patientName: "Sophia Williams", date: "2026-05-08", time: "9:00 AM",  type: "Consultation",  coordinator: "Emily Watson",      status: "Completed" },
  { id: "A006", patientId: "W006", patientName: "James Patel",     date: "2026-05-09", time: "7:30 AM",  type: "Assessment",    coordinator: "Sarah Lee",         status: "Completed" },
  { id: "A007", patientId: "W007", patientName: "Aisha Rahman",    date: "2026-05-17", time: "1:00 PM",  type: "Coaching",      coordinator: "Dr. Priya Sharma",  status: "Scheduled" },
  { id: "A008", patientId: "W008", patientName: "Carlos Martinez", date: "2026-05-06", time: "4:00 PM",  type: "Follow-up",     coordinator: "Dr. James Carter",  status: "Cancelled" },
];

export const medications: Medication[] = [
  { id: "MED001", patientId: "W002", patientName: "Marcus Brown",    name: "Lisinopril",          dosage: "10mg",  frequency: "Once daily",       startDate: "2026-02-20", prescribedBy: "Dr. James Carter",  category: "Cardiovascular",          status: "Active",    notes: "Take in the morning with water" },
  { id: "MED002", patientId: "W002", patientName: "Marcus Brown",    name: "Atorvastatin",        dosage: "20mg",  frequency: "Once daily",       startDate: "2026-02-20", prescribedBy: "Dr. James Carter",  category: "Cardiovascular",          status: "Active",    notes: "Take in the evening" },
  { id: "MED003", patientId: "W004", patientName: "Robert Davis",    name: "Metformin",           dosage: "500mg", frequency: "Twice daily",      startDate: "2026-01-10", prescribedBy: "Dr. Priya Sharma",  category: "Diabetes",                status: "Active",    notes: "Take with meals" },
  { id: "MED004", patientId: "W004", patientName: "Robert Davis",    name: "Glipizide",           dosage: "5mg",   frequency: "Before breakfast", startDate: "2026-03-01", prescribedBy: "Dr. Priya Sharma",  category: "Diabetes",                status: "Active" },
  { id: "MED005", patientId: "W001", patientName: "Emma Johnson",    name: "Vitamin D3",          dosage: "2000IU",frequency: "Once daily",       startDate: "2026-03-15", prescribedBy: "Sarah Lee",         category: "Vitamins & Supplements",  status: "Active" },
  { id: "MED006", patientId: "W001", patientName: "Emma Johnson",    name: "Iron Supplement",     dosage: "65mg",  frequency: "Once daily",       startDate: "2026-03-15", prescribedBy: "Sarah Lee",         category: "Vitamins & Supplements",  status: "Paused",    notes: "Pause if GI discomfort occurs" },
  { id: "MED007", patientId: "W005", patientName: "Sophia Williams", name: "Sertraline",          dosage: "50mg",  frequency: "Once daily",       startDate: "2026-02-14", prescribedBy: "Emily Watson",      category: "Mental Health",           status: "Active",    notes: "Do not stop abruptly" },
  { id: "MED008", patientId: "W005", patientName: "Sophia Williams", name: "Magnesium Glycinate", dosage: "400mg", frequency: "Before bed",       startDate: "2026-03-01", prescribedBy: "Emily Watson",      category: "Vitamins & Supplements",  status: "Active" },
  { id: "MED009", patientId: "W008", patientName: "Carlos Martinez", name: "Amlodipine",          dosage: "5mg",   frequency: "Once daily",       startDate: "2026-01-28", prescribedBy: "Dr. James Carter",  category: "Cardiovascular",          status: "Active" },
  { id: "MED010", patientId: "W008", patientName: "Carlos Martinez", name: "Rosuvastatin",        dosage: "10mg",  frequency: "Once daily",       startDate: "2026-01-28", prescribedBy: "Dr. James Carter",  category: "Cardiovascular",          status: "Active",    notes: "Avoid grapefruit juice" },
  { id: "MED011", patientId: "W006", patientName: "James Patel",     name: "Creatine Monohydrate",dosage: "5g",    frequency: "Once daily",       startDate: "2026-03-22", prescribedBy: "Sarah Lee",         category: "Vitamins & Supplements",  status: "Active" },
  { id: "MED012", patientId: "W007", patientName: "Aisha Rahman",    name: "Probiotic Complex",   dosage: "10B CFU",frequency:"Once daily",       startDate: "2026-04-05", prescribedBy: "Dr. Priya Sharma",  category: "General",                 status: "Active",    notes: "Take with breakfast" },
  { id: "MED013", patientId: "W003", patientName: "Lisa Chen",       name: "Melatonin",           dosage: "3mg",   frequency: "Before bed",       startDate: "2026-03-01", endDate: "2026-04-30", prescribedBy: "Emily Watson", category: "General", status: "Completed", notes: "Course completed" },
];

export const vitals: Vital[] = [
  { id: "V001", patientId: "W001", type: "Steps",            value: 8750,  unit: "steps", timestamp: "2026-05-07", trend: "up" },
  { id: "V002", patientId: "W001", type: "HeartRate",        value: 68,    unit: "bpm",   timestamp: "2026-05-07", trend: "stable" },
  { id: "V003", patientId: "W002", type: "HeartRate",        value: 72,    unit: "bpm",   timestamp: "2026-05-07", trend: "down" },
  { id: "V004", patientId: "W002", type: "BloodPressure",    value: 138,   unit: "mmHg",  timestamp: "2026-05-07", trend: "down" },
  { id: "V005", patientId: "W003", type: "Temperature",      value: 98.6,  unit: "°F",    timestamp: "2026-05-07", trend: "stable" },
  { id: "V006", patientId: "W004", type: "BloodPressure",    value: 142,   unit: "mmHg",  timestamp: "2026-05-07", trend: "up" },
  { id: "V007", patientId: "W006", type: "HeartRate",        value: 58,    unit: "bpm",   timestamp: "2026-05-07", trend: "stable" },
  { id: "V008", patientId: "W008", type: "BloodPressure",    value: 148,   unit: "mmHg",  timestamp: "2026-05-07", trend: "up" },
];

export const vitalsHistory: VitalHistory[] = [
  { patientId: "ALL", week: "Week 1", heartRate: 76, bloodPressure: 145, temperature: 98.4, steps: 6800 },
  { patientId: "ALL", week: "Week 2", heartRate: 74, bloodPressure: 142, temperature: 98.5, steps: 7200 },
  { patientId: "ALL", week: "Week 3", heartRate: 72, bloodPressure: 138, temperature: 98.5, steps: 8100 },
  { patientId: "ALL", week: "Week 4", heartRate: 70, bloodPressure: 135, temperature: 98.6, steps: 8750 },
];

export const wellnessTrendData = [
  { week: "W1", wellness: 65, thriving: 2, monitoring: 3, attention: 3 },
  { week: "W2", wellness: 68, thriving: 3, monitoring: 3, attention: 2 },
  { week: "W3", wellness: 72, thriving: 4, monitoring: 2, attention: 2 },
  { week: "W4", wellness: 78, thriving: 5, monitoring: 2, attention: 1 },
];

export const dashboardStats = {
  total: wellnessPatients.length,
  active: wellnessPatients.filter(p => p.status === "Thriving" || p.status === "Monitoring").length,
  appointments: appointments.filter(a => a.status === "Scheduled").length,
  goalsCompleted: wellnessGoals.filter(g => g.status === "Completed").length,
};